### ISSUE TITLE
Is this a bug ? 

### ISSUE THREAD

**Issue by slowbull** [cgel/DRL#3]
In your code [RM.add(state, action, reward, terminal)]( https://github.com/cgel/DRL/blob/master/agents/baseAgent.py#L56-L56) in BaseAgent,  timestep of self.game_state[:, :, :, -1] self.game_action self.game_reward seem not consistent. your self.game_reward is not the reward when you take action self.game_action on self.game_state[:,:,;-1], however, it is the reward you got from last step.

**Comment by cgel** [comment]
If step is called we know that the game did not end, so we add everything from the last step - last screen , last reward, last action.
